(define (or-gate-composite a1 a2 output)
  (let ((not-a1 (make-wire))
        (not-a2 (make-wire))
        (temp (make-wire)))
    (inverter a1 not-a1)
    (inverter a2 not-a2)
    (and-gate not-a1 not-a2 temp)
    (inverter temp output))
  'ok)