(define (make-account balance passwd)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw method)
    (cond ((eq? pw passwd)
           (cond ((eq? method 'withdraw) withdraw)
                 ((eq? method 'deposit) deposit)
                 (else (printf "unknown method ~a" method))))
          (else (lambda (amount) "incorrect password"))))
  dispatch)