(define (make-account balance passwd)
  (define (call-the-cops)
    "cops are coming for you!!!!")
  (let ((counter 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch pw method)
      (cond ((eq? pw passwd)
             (set! counter 0)
             (cond ((eq? method 'withdraw) withdraw)
                   ((eq? method 'deposit) deposit)
                   (else (printf "unknown method ~a" method))))
            (else 
             (lambda (amount) 
               (set! counter (+ counter 1))
               (if (> counter 7)
                   (call-the-cops)
                   (printf "incorrect password, you have ~a times to try" (- 7 counter)))))))
    dispatch))