(define (make-account balance passwd)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (add-password new-passwd)
    (set! password-list (cons new-passwd password-list)))
  (define (dispatch pw method)
    (cond ((eq? pw passwd)
           (cond ((eq? method 'withdraw) withdraw)
                 ((eq? method 'deposit) deposit)
                 ((eq? method 'add-password) add-password)
                 (else (lambda (amount) "unknown method"))))
          (else (lambda (amount) "incorrect password"))))
  dispatch)

(define (make-joint account password new-password)
  (define (access-account pw method)
    (if (eq? pw new-password)
        (account password method)
        (lambda (amount) "incorrect password")))
  access-account)

(define peter (make-account 100 'open-sesame))
(define paul (make-joint peter 'open-sesame 'rosebud))